apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters 
      rolearn : arn:aws:iam::447282627868:role/UdacityFlaskDeployCBKubectlRole 
      username: build
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::447282627868:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-U29X6QTUEBRP
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2022-10-10T16:08:40Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1687"
  uid: 0539b246-aa6b-45ea-b272-4f59f1f7f326
