apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters 
      rolearn : arn:aws:iam::447282627868:role/UdacityFlaskDeployCBKubectlRole 
      username: build
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::447282627868:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-J3VMTBU61DU6
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2022-10-12T10:56:06Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1645"
  uid: 604b30b1-139e-41c5-a64b-8f3785b80c69
